[2025-07-07T15:17:28.374+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-07T15:17:28.396+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_lakehouse_project.dbt_test manual__2025-07-07T15:17:21.038117+00:00 [queued]>
[2025-07-07T15:17:28.403+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_lakehouse_project.dbt_test manual__2025-07-07T15:17:21.038117+00:00 [queued]>
[2025-07-07T15:17:28.403+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-07T15:17:28.412+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2025-07-07 15:17:21.038117+00:00
[2025-07-07T15:17:28.419+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_lakehouse_project', 'dbt_test', 'manual__2025-07-07T15:17:21.038117+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpyrr4to0x']
[2025-07-07T15:17:28.421+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask dbt_test
[2025-07-07T15:17:28.422+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1957) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-07T15:17:28.422+0000] {standard_task_runner.py:63} INFO - Started process 1958 to run task
[2025-07-07T15:17:28.450+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_lakehouse_project.dbt_test manual__2025-07-07T15:17:21.038117+00:00 [running]> on host 4548c9e5e95e
[2025-07-07T15:17:28.503+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_lakehouse_project' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T15:17:21.038117+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T15:17:21.038117+00:00'
[2025-07-07T15:17:28.504+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-07T15:17:28.515+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-07T15:17:28.516+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt_lakehouse && dbt test']
[2025-07-07T15:17:28.523+0000] {subprocess.py:86} INFO - Output:
[2025-07-07T15:17:30.167+0000] {subprocess.py:93} INFO - [0m15:17:30  Running with dbt=1.10.3
[2025-07-07T15:17:30.182+0000] {subprocess.py:93} INFO - WARNING:thrift.transport.sslcompat:using legacy validation callback
[2025-07-07T15:17:30.383+0000] {subprocess.py:93} INFO - [0m15:17:30  Registered adapter: spark=1.9.2
[2025-07-07T15:17:30.543+0000] {subprocess.py:93} INFO - [0m15:17:30  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-07-07T15:17:30.543+0000] {subprocess.py:93} INFO - There are 2 unused configuration paths:
[2025-07-07T15:17:30.543+0000] {subprocess.py:93} INFO - - models.dbt_lakehouse.staging
[2025-07-07T15:17:30.544+0000] {subprocess.py:93} INFO - - models.dbt_lakehouse.intermediate
[2025-07-07T15:17:30.673+0000] {subprocess.py:93} INFO - [0m15:17:30  Found 3 models, 6 data tests, 1 source, 473 macros
[2025-07-07T15:17:30.675+0000] {subprocess.py:93} INFO - [0m15:17:30
[2025-07-07T15:17:30.675+0000] {subprocess.py:93} INFO - [0m15:17:30  Concurrency: 1 threads (target='dev')
[2025-07-07T15:17:30.675+0000] {subprocess.py:93} INFO - [0m15:17:30
[2025-07-07T15:17:30.826+0000] {subprocess.py:93} INFO - [0m15:17:30  1 of 6 START test not_null_fct_summary_customer_id ............................. [RUN]
[2025-07-07T15:17:31.162+0000] {subprocess.py:93} INFO - [0m15:17:31  1 of 6 PASS not_null_fct_summary_customer_id ................................... [[32mPASS[0m in 0.33s]
[2025-07-07T15:17:31.164+0000] {subprocess.py:93} INFO - [0m15:17:31  2 of 6 START test not_null_my_first_dbt_model_id ............................... [RUN]
[2025-07-07T15:17:31.400+0000] {subprocess.py:93} INFO - [0m15:17:31  2 of 6 FAIL 1 not_null_my_first_dbt_model_id ................................... [[31mFAIL 1[0m in 0.24s]
[2025-07-07T15:17:31.402+0000] {subprocess.py:93} INFO - [0m15:17:31  3 of 6 START test not_null_my_second_dbt_model_id .............................. [RUN]
[2025-07-07T15:17:31.612+0000] {subprocess.py:93} INFO - [0m15:17:31  3 of 6 PASS not_null_my_second_dbt_model_id .................................... [[32mPASS[0m in 0.21s]
[2025-07-07T15:17:31.614+0000] {subprocess.py:93} INFO - [0m15:17:31  4 of 6 START test unique_fct_summary_customer_id ............................... [RUN]
[2025-07-07T15:17:32.201+0000] {subprocess.py:93} INFO - [0m15:17:32  4 of 6 FAIL 3 unique_fct_summary_customer_id ................................... [[31mFAIL 3[0m in 0.59s]
[2025-07-07T15:17:32.202+0000] {subprocess.py:93} INFO - [0m15:17:32  5 of 6 START test unique_my_first_dbt_model_id ................................. [RUN]
[2025-07-07T15:17:32.596+0000] {subprocess.py:93} INFO - [0m15:17:32  5 of 6 PASS unique_my_first_dbt_model_id ....................................... [[32mPASS[0m in 0.39s]
[2025-07-07T15:17:32.598+0000] {subprocess.py:93} INFO - [0m15:17:32  6 of 6 START test unique_my_second_dbt_model_id ................................ [RUN]
[2025-07-07T15:17:32.952+0000] {subprocess.py:93} INFO - [0m15:17:32  6 of 6 FAIL 1 unique_my_second_dbt_model_id .................................... [[31mFAIL 1[0m in 0.35s]
[2025-07-07T15:17:32.986+0000] {subprocess.py:93} INFO - [0m15:17:32
[2025-07-07T15:17:32.986+0000] {subprocess.py:93} INFO - [0m15:17:32  Finished running 6 data tests in 0 hours 0 minutes and 2.31 seconds (2.31s).
[2025-07-07T15:17:33.029+0000] {subprocess.py:93} INFO - [0m15:17:33
[2025-07-07T15:17:33.030+0000] {subprocess.py:93} INFO - [0m15:17:33  [31mCompleted with 3 errors, 0 partial successes, and 0 warnings:[0m
[2025-07-07T15:17:33.030+0000] {subprocess.py:93} INFO - [0m15:17:33
[2025-07-07T15:17:33.031+0000] {subprocess.py:93} INFO - [0m15:17:33  [31mFailure in test not_null_my_first_dbt_model_id (models/example/schema.yml)[0m
[2025-07-07T15:17:33.031+0000] {subprocess.py:93} INFO - [0m15:17:33    Got 1 result, configured to fail if != 0
[2025-07-07T15:17:33.031+0000] {subprocess.py:93} INFO - [0m15:17:33
[2025-07-07T15:17:33.032+0000] {subprocess.py:93} INFO - [0m15:17:33    compiled code at target/compiled/dbt_lakehouse/models/example/schema.yml/not_null_my_first_dbt_model_id.sql
[2025-07-07T15:17:33.032+0000] {subprocess.py:93} INFO - [0m15:17:33
[2025-07-07T15:17:33.033+0000] {subprocess.py:93} INFO - [0m15:17:33  [31mFailure in test unique_fct_summary_customer_id (models/marts/schema.yml)[0m
[2025-07-07T15:17:33.033+0000] {subprocess.py:93} INFO - [0m15:17:33    Got 3 results, configured to fail if != 0
[2025-07-07T15:17:33.034+0000] {subprocess.py:93} INFO - [0m15:17:33
[2025-07-07T15:17:33.034+0000] {subprocess.py:93} INFO - [0m15:17:33    compiled code at target/compiled/dbt_lakehouse/models/marts/schema.yml/unique_fct_summary_customer_id.sql
[2025-07-07T15:17:33.035+0000] {subprocess.py:93} INFO - [0m15:17:33
[2025-07-07T15:17:33.035+0000] {subprocess.py:93} INFO - [0m15:17:33  [31mFailure in test unique_my_second_dbt_model_id (models/example/schema.yml)[0m
[2025-07-07T15:17:33.036+0000] {subprocess.py:93} INFO - [0m15:17:33    Got 1 result, configured to fail if != 0
[2025-07-07T15:17:33.036+0000] {subprocess.py:93} INFO - [0m15:17:33
[2025-07-07T15:17:33.037+0000] {subprocess.py:93} INFO - [0m15:17:33    compiled code at target/compiled/dbt_lakehouse/models/example/schema.yml/unique_my_second_dbt_model_id.sql
[2025-07-07T15:17:33.037+0000] {subprocess.py:93} INFO - [0m15:17:33
[2025-07-07T15:17:33.037+0000] {subprocess.py:93} INFO - [0m15:17:33  Done. PASS=3 WARN=0 ERROR=3 SKIP=0 NO-OP=0 TOTAL=6
[2025-07-07T15:17:33.267+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-07T15:17:33.268+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-07T15:17:33.275+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-07T15:17:33.277+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_run_lakehouse_project, task_id=dbt_test, run_id=manual__2025-07-07T15:17:21.038117+00:00, execution_date=20250707T151721, start_date=20250707T151728, end_date=20250707T151733
[2025-07-07T15:17:33.286+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 1958)
[2025-07-07T15:17:33.329+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-07T15:17:33.361+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-07T15:17:33.364+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
