[2025-07-07T06:46:57.893+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-07T06:46:57.917+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_lakehouse_project.dbt_run_all manual__2025-07-07T06:46:56.958652+00:00 [queued]>
[2025-07-07T06:46:57.924+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_lakehouse_project.dbt_run_all manual__2025-07-07T06:46:56.958652+00:00 [queued]>
[2025-07-07T06:46:57.925+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-07T06:46:57.937+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run_all> on 2025-07-07 06:46:56.958652+00:00
[2025-07-07T06:46:57.943+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_lakehouse_project', 'dbt_run_all', 'manual__2025-07-07T06:46:56.958652+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp_r9e6731']
[2025-07-07T06:46:57.945+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask dbt_run_all
[2025-07-07T06:46:57.945+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1182) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-07T06:46:57.946+0000] {standard_task_runner.py:63} INFO - Started process 1185 to run task
[2025-07-07T06:46:57.980+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_lakehouse_project.dbt_run_all manual__2025-07-07T06:46:56.958652+00:00 [running]> on host 5ff4c7b39ece
[2025-07-07T06:46:58.043+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_lakehouse_project' AIRFLOW_CTX_TASK_ID='dbt_run_all' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T06:46:56.958652+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T06:46:56.958652+00:00'
[2025-07-07T06:46:58.044+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-07T06:46:58.056+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-07T06:46:58.056+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt_lakehouse && dbt run']
[2025-07-07T06:46:58.066+0000] {subprocess.py:86} INFO - Output:
[2025-07-07T06:46:59.987+0000] {subprocess.py:93} INFO - [0m06:46:59  Running with dbt=1.10.3
[2025-07-07T06:47:00.021+0000] {subprocess.py:93} INFO - INFO:trino.auth:keyring module not found. OAuth2 token will not be stored in keyring.
[2025-07-07T06:47:00.023+0000] {subprocess.py:93} INFO - INFO:trino.auth:keyring module not found. OAuth2 token will not be stored in keyring.
[2025-07-07T06:47:00.221+0000] {subprocess.py:93} INFO - [0m06:47:00  Registered adapter: trino=1.9.2
[2025-07-07T06:47:00.385+0000] {subprocess.py:93} INFO - [0m06:47:00  Unable to do partial parsing because a project config has changed
[2025-07-07T06:47:01.606+0000] {subprocess.py:93} INFO - [0m06:47:01  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-07-07T06:47:01.606+0000] {subprocess.py:93} INFO - There are 2 unused configuration paths:
[2025-07-07T06:47:01.606+0000] {subprocess.py:93} INFO - - models.dbt_lakehouse.intermediate
[2025-07-07T06:47:01.606+0000] {subprocess.py:93} INFO - - models.dbt_lakehouse.staging
[2025-07-07T06:47:01.696+0000] {subprocess.py:93} INFO - [0m06:47:01  Found 3 models, 6 data tests, 1 source, 454 macros
[2025-07-07T06:47:01.698+0000] {subprocess.py:93} INFO - [0m06:47:01
[2025-07-07T06:47:01.698+0000] {subprocess.py:93} INFO - [0m06:47:01  Concurrency: 1 threads (target='dev')
[2025-07-07T06:47:01.698+0000] {subprocess.py:93} INFO - [0m06:47:01
[2025-07-07T06:47:01.738+0000] {subprocess.py:93} INFO - [0m06:47:01  [[33mWARNING[0m]: SSL certificate validation is disabled by default. It is legacy behavior which will be changed in future releases. It is strongly advised to enable `require_certificate_validation` flag or explicitly set `cert` configuration to `True` for security reasons. You may receive an error after that if your SSL setup is incorrect.
[2025-07-07T06:47:01.738+0000] {subprocess.py:93} INFO - You may opt into the new behavior sooner by setting `flags.require_certificate_validation` to `True` in `dbt_project.yml`.
[2025-07-07T06:47:01.738+0000] {subprocess.py:93} INFO - Visit https://docs.getdbt.com/reference/global-configs/behavior-changes for more information.
[2025-07-07T06:47:03.128+0000] {subprocess.py:93} INFO - [0m06:47:03  1 of 3 START sql table model default_marts.fct_summary ......................... [RUN]
[2025-07-07T06:47:03.950+0000] {subprocess.py:93} INFO - [0m06:47:03  1 of 3 OK created sql table model default_marts.fct_summary .................... [[32mCREATE TABLE (3 rows)[0m in 0.82s]
[2025-07-07T06:47:03.955+0000] {subprocess.py:93} INFO - [0m06:47:03  2 of 3 START sql table model default_staging.my_first_dbt_model ................ [RUN]
[2025-07-07T06:47:04.317+0000] {subprocess.py:93} INFO - [0m06:47:04  2 of 3 ERROR creating sql table model default_staging.my_first_dbt_model ....... [[31mERROR[0m in 0.36s]
[2025-07-07T06:47:04.344+0000] {subprocess.py:93} INFO - [0m06:47:04  3 of 3 SKIP relation default_staging.my_second_dbt_model ....................... [[33mSKIP[0m]
[2025-07-07T06:47:04.347+0000] {subprocess.py:93} INFO - [0m06:47:04
[2025-07-07T06:47:04.347+0000] {subprocess.py:93} INFO - [0m06:47:04  Finished running 2 table models, 1 view model in 0 hours 0 minutes and 2.65 seconds (2.65s).
[2025-07-07T06:47:04.380+0000] {subprocess.py:93} INFO - [0m06:47:04
[2025-07-07T06:47:04.380+0000] {subprocess.py:93} INFO - [0m06:47:04  [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[2025-07-07T06:47:04.381+0000] {subprocess.py:93} INFO - [0m06:47:04
[2025-07-07T06:47:04.382+0000] {subprocess.py:93} INFO - [0m06:47:04  [31mFailure in model my_first_dbt_model (models/example/my_first_dbt_model.sql)[0m
[2025-07-07T06:47:04.382+0000] {subprocess.py:93} INFO - [0m06:47:04    Database Error in model my_first_dbt_model (models/example/my_first_dbt_model.sql)
[2025-07-07T06:47:04.383+0000] {subprocess.py:93} INFO -   TrinoExternalError(type=EXTERNAL, name=DELTA_LAKE_BAD_WRITE, message="Failed to write Delta Lake transaction log entry", query_id=20250707_064703_00021_884xn)
[2025-07-07T06:47:04.383+0000] {subprocess.py:93} INFO -   compiled code at target/run/dbt_lakehouse/models/example/my_first_dbt_model.sql
[2025-07-07T06:47:04.383+0000] {subprocess.py:93} INFO - [0m06:47:04
[2025-07-07T06:47:04.383+0000] {subprocess.py:93} INFO - [0m06:47:04    compiled code at target/compiled/dbt_lakehouse/models/example/my_first_dbt_model.sql
[2025-07-07T06:47:04.384+0000] {subprocess.py:93} INFO - [0m06:47:04
[2025-07-07T06:47:04.384+0000] {subprocess.py:93} INFO - [0m06:47:04  Done. PASS=1 WARN=0 ERROR=1 SKIP=1 NO-OP=0 TOTAL=3
[2025-07-07T06:47:04.790+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-07T06:47:04.790+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-07T06:47:04.799+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-07T06:47:04.804+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_run_lakehouse_project, task_id=dbt_run_all, run_id=manual__2025-07-07T06:46:56.958652+00:00, execution_date=20250707T064656, start_date=20250707T064657, end_date=20250707T064704
[2025-07-07T06:47:04.815+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task dbt_run_all (Bash command failed. The command returned a non-zero exit code 1.; 1185)
[2025-07-07T06:47:04.860+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-07T06:47:04.878+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-07T06:47:04.881+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
