[2025-07-07T07:27:02.061+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-07T07:27:02.091+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_lakehouse_project.dbt_run_all manual__2025-07-07T07:27:01.292031+00:00 [queued]>
[2025-07-07T07:27:02.096+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_lakehouse_project.dbt_run_all manual__2025-07-07T07:27:01.292031+00:00 [queued]>
[2025-07-07T07:27:02.097+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-07T07:27:02.111+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run_all> on 2025-07-07 07:27:01.292031+00:00
[2025-07-07T07:27:02.120+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_lakehouse_project', 'dbt_run_all', 'manual__2025-07-07T07:27:01.292031+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpg5b4fmba']
[2025-07-07T07:27:02.122+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask dbt_run_all
[2025-07-07T07:27:02.123+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1214) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-07T07:27:02.124+0000] {standard_task_runner.py:63} INFO - Started process 1216 to run task
[2025-07-07T07:27:02.153+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_lakehouse_project.dbt_run_all manual__2025-07-07T07:27:01.292031+00:00 [running]> on host fb8ac4917e48
[2025-07-07T07:27:02.213+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_lakehouse_project' AIRFLOW_CTX_TASK_ID='dbt_run_all' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T07:27:01.292031+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T07:27:01.292031+00:00'
[2025-07-07T07:27:02.214+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-07T07:27:02.226+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-07T07:27:02.227+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt_lakehouse && dbt run']
[2025-07-07T07:27:02.239+0000] {subprocess.py:86} INFO - Output:
[2025-07-07T07:27:04.120+0000] {subprocess.py:93} INFO - [0m07:27:04  Running with dbt=1.10.3
[2025-07-07T07:27:04.152+0000] {subprocess.py:93} INFO - INFO:trino.auth:keyring module not found. OAuth2 token will not be stored in keyring.
[2025-07-07T07:27:04.154+0000] {subprocess.py:93} INFO - INFO:trino.auth:keyring module not found. OAuth2 token will not be stored in keyring.
[2025-07-07T07:27:04.342+0000] {subprocess.py:93} INFO - [0m07:27:04  Registered adapter: trino=1.9.2
[2025-07-07T07:27:04.533+0000] {subprocess.py:93} INFO - [0m07:27:04  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-07-07T07:27:04.533+0000] {subprocess.py:93} INFO - There are 2 unused configuration paths:
[2025-07-07T07:27:04.533+0000] {subprocess.py:93} INFO - - models.dbt_lakehouse.intermediate
[2025-07-07T07:27:04.533+0000] {subprocess.py:93} INFO - - models.dbt_lakehouse.staging
[2025-07-07T07:27:04.674+0000] {subprocess.py:93} INFO - [0m07:27:04  Found 3 models, 6 data tests, 1 source, 454 macros
[2025-07-07T07:27:04.675+0000] {subprocess.py:93} INFO - [0m07:27:04
[2025-07-07T07:27:04.676+0000] {subprocess.py:93} INFO - [0m07:27:04  Concurrency: 1 threads (target='dev')
[2025-07-07T07:27:04.676+0000] {subprocess.py:93} INFO - [0m07:27:04
[2025-07-07T07:27:04.736+0000] {subprocess.py:93} INFO - [0m07:27:04  [[33mWARNING[0m]: SSL certificate validation is disabled by default. It is legacy behavior which will be changed in future releases. It is strongly advised to enable `require_certificate_validation` flag or explicitly set `cert` configuration to `True` for security reasons. You may receive an error after that if your SSL setup is incorrect.
[2025-07-07T07:27:04.737+0000] {subprocess.py:93} INFO - You may opt into the new behavior sooner by setting `flags.require_certificate_validation` to `True` in `dbt_project.yml`.
[2025-07-07T07:27:04.737+0000] {subprocess.py:93} INFO - Visit https://docs.getdbt.com/reference/global-configs/behavior-changes for more information.
[2025-07-07T07:27:06.375+0000] {subprocess.py:93} INFO - [0m07:27:06  1 of 3 START sql table model default_marts.fct_summary ......................... [RUN]
[2025-07-07T07:27:07.208+0000] {subprocess.py:93} INFO - [0m07:27:07  1 of 3 ERROR creating sql table model default_marts.fct_summary ................ [[31mERROR[0m in 0.83s]
[2025-07-07T07:27:07.211+0000] {subprocess.py:93} INFO - [0m07:27:07  2 of 3 START sql table model default_staging.my_first_dbt_model ................ [RUN]
[2025-07-07T07:27:07.472+0000] {subprocess.py:93} INFO - [0m07:27:07  2 of 3 OK created sql table model default_staging.my_first_dbt_model ........... [[32mCREATE TABLE (2 rows)[0m in 0.26s]
[2025-07-07T07:27:07.475+0000] {subprocess.py:93} INFO - [0m07:27:07  3 of 3 START sql table model default_staging.my_second_dbt_model ............... [RUN]
[2025-07-07T07:27:07.677+0000] {subprocess.py:93} INFO - [0m07:27:07  3 of 3 OK created sql table model default_staging.my_second_dbt_model .......... [[32mCREATE TABLE (1 rows)[0m in 0.20s]
[2025-07-07T07:27:07.681+0000] {subprocess.py:93} INFO - [0m07:27:07
[2025-07-07T07:27:07.682+0000] {subprocess.py:93} INFO - [0m07:27:07  Finished running 3 table models in 0 hours 0 minutes and 3.00 seconds (3.00s).
[2025-07-07T07:27:07.713+0000] {subprocess.py:93} INFO - [0m07:27:07
[2025-07-07T07:27:07.714+0000] {subprocess.py:93} INFO - [0m07:27:07  [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[2025-07-07T07:27:07.714+0000] {subprocess.py:93} INFO - [0m07:27:07
[2025-07-07T07:27:07.714+0000] {subprocess.py:93} INFO - [0m07:27:07  [31mFailure in model fct_summary (models/marts/fct_summary.sql)[0m
[2025-07-07T07:27:07.715+0000] {subprocess.py:93} INFO - [0m07:27:07    Database Error in model fct_summary (models/marts/fct_summary.sql)
[2025-07-07T07:27:07.715+0000] {subprocess.py:93} INFO -   TrinoExternalError(type=EXTERNAL, name=DELTA_LAKE_BAD_WRITE, message="Failed to write Delta Lake transaction log entry", query_id=20250707_072706_00019_kn9qh)
[2025-07-07T07:27:07.715+0000] {subprocess.py:93} INFO -   compiled code at target/run/dbt_lakehouse/models/marts/fct_summary.sql
[2025-07-07T07:27:07.715+0000] {subprocess.py:93} INFO - [0m07:27:07
[2025-07-07T07:27:07.715+0000] {subprocess.py:93} INFO - [0m07:27:07    compiled code at target/compiled/dbt_lakehouse/models/marts/fct_summary.sql
[2025-07-07T07:27:07.716+0000] {subprocess.py:93} INFO - [0m07:27:07
[2025-07-07T07:27:07.716+0000] {subprocess.py:93} INFO - [0m07:27:07  Done. PASS=2 WARN=0 ERROR=1 SKIP=0 NO-OP=0 TOTAL=3
[2025-07-07T07:27:07.972+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-07T07:27:07.972+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-07T07:27:07.979+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-07T07:27:07.981+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_run_lakehouse_project, task_id=dbt_run_all, run_id=manual__2025-07-07T07:27:01.292031+00:00, execution_date=20250707T072701, start_date=20250707T072702, end_date=20250707T072707
[2025-07-07T07:27:08.032+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task dbt_run_all (Bash command failed. The command returned a non-zero exit code 1.; 1216)
[2025-07-07T07:27:08.079+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-07T07:27:08.098+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-07T07:27:08.101+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
