[2025-07-06T05:45:55.016+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-06T05:45:55.037+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lakehouse_pipeline.silver_to_gold manual__2025-07-06T05:45:10.046449+00:00 [queued]>
[2025-07-06T05:45:55.043+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lakehouse_pipeline.silver_to_gold manual__2025-07-06T05:45:10.046449+00:00 [queued]>
[2025-07-06T05:45:55.043+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-06T05:45:55.052+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): silver_to_gold> on 2025-07-06 05:45:10.046449+00:00
[2025-07-06T05:45:55.059+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'lakehouse_pipeline', 'silver_to_gold', 'manual__2025-07-06T05:45:10.046449+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmps11qdpyp']
[2025-07-06T05:45:55.060+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask silver_to_gold
[2025-07-06T05:45:55.061+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=510) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-06T05:45:55.062+0000] {standard_task_runner.py:63} INFO - Started process 511 to run task
[2025-07-06T05:45:55.088+0000] {task_command.py:426} INFO - Running <TaskInstance: lakehouse_pipeline.silver_to_gold manual__2025-07-06T05:45:10.046449+00:00 [running]> on host 888662e513aa
[2025-07-06T05:45:55.139+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lakehouse_pipeline' AIRFLOW_CTX_TASK_ID='silver_to_gold' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T05:45:10.046449+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T05:45:10.046449+00:00'
[2025-07-06T05:45:55.140+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-06T05:46:04.425+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-06T05:46:04.426+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/silver_to_gold.py", line 27, in run
    summary.write.format("delta").mode("overwrite").save(gold_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/readwriter.py", line 1398, in save
    self._jwrite.save(path)
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/errors/exceptions/captured.py", line 175, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: Failed to merge fields 'customer_id' and 'customer_id'. Failed to merge incompatible data types IntegerType and StringType
[2025-07-06T05:46:04.438+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=lakehouse_pipeline, task_id=silver_to_gold, run_id=manual__2025-07-06T05:45:10.046449+00:00, execution_date=20250706T054510, start_date=20250706T054555, end_date=20250706T054604
[2025-07-06T05:46:04.449+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task silver_to_gold (Failed to merge fields 'customer_id' and 'customer_id'. Failed to merge incompatible data types IntegerType and StringType; 511)
[2025-07-06T05:46:04.460+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-06T05:46:04.479+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-06T05:46:04.482+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
