[2025-07-07T06:46:57.894+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-07T06:46:57.918+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_lakehouse_project.dbt_run_all scheduled__2025-07-05T10:00:00+00:00 [queued]>
[2025-07-07T06:46:57.925+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_lakehouse_project.dbt_run_all scheduled__2025-07-05T10:00:00+00:00 [queued]>
[2025-07-07T06:46:57.925+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-07T06:46:57.937+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run_all> on 2025-07-05 10:00:00+00:00
[2025-07-07T06:46:57.946+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1183) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-07T06:46:57.946+0000] {standard_task_runner.py:63} INFO - Started process 1184 to run task
[2025-07-07T06:46:57.946+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_lakehouse_project', 'dbt_run_all', 'scheduled__2025-07-05T10:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp5jmozzy2']
[2025-07-07T06:46:57.947+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask dbt_run_all
[2025-07-07T06:46:57.981+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_lakehouse_project.dbt_run_all scheduled__2025-07-05T10:00:00+00:00 [running]> on host 5ff4c7b39ece
[2025-07-07T06:46:58.043+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_lakehouse_project' AIRFLOW_CTX_TASK_ID='dbt_run_all' AIRFLOW_CTX_EXECUTION_DATE='2025-07-05T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-05T10:00:00+00:00'
[2025-07-07T06:46:58.044+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-07T06:46:58.056+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-07T06:46:58.056+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt_lakehouse && dbt run']
[2025-07-07T06:46:58.066+0000] {subprocess.py:86} INFO - Output:
[2025-07-07T06:46:59.981+0000] {subprocess.py:93} INFO - [0m06:46:59  Running with dbt=1.10.3
[2025-07-07T06:47:00.017+0000] {subprocess.py:93} INFO - INFO:trino.auth:keyring module not found. OAuth2 token will not be stored in keyring.
[2025-07-07T06:47:00.019+0000] {subprocess.py:93} INFO - INFO:trino.auth:keyring module not found. OAuth2 token will not be stored in keyring.
[2025-07-07T06:47:00.218+0000] {subprocess.py:93} INFO - [0m06:47:00  Registered adapter: trino=1.9.2
[2025-07-07T06:47:00.383+0000] {subprocess.py:93} INFO - [0m06:47:00  Unable to do partial parsing because a project config has changed
[2025-07-07T06:47:01.603+0000] {subprocess.py:93} INFO - [0m06:47:01  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-07-07T06:47:01.604+0000] {subprocess.py:93} INFO - There are 2 unused configuration paths:
[2025-07-07T06:47:01.604+0000] {subprocess.py:93} INFO - - models.dbt_lakehouse.intermediate
[2025-07-07T06:47:01.604+0000] {subprocess.py:93} INFO - - models.dbt_lakehouse.staging
[2025-07-07T06:47:01.695+0000] {subprocess.py:93} INFO - [0m06:47:01  Found 3 models, 6 data tests, 1 source, 454 macros
[2025-07-07T06:47:01.697+0000] {subprocess.py:93} INFO - [0m06:47:01
[2025-07-07T06:47:01.697+0000] {subprocess.py:93} INFO - [0m06:47:01  Concurrency: 1 threads (target='dev')
[2025-07-07T06:47:01.698+0000] {subprocess.py:93} INFO - [0m06:47:01
[2025-07-07T06:47:01.737+0000] {subprocess.py:93} INFO - [0m06:47:01  [[33mWARNING[0m]: SSL certificate validation is disabled by default. It is legacy behavior which will be changed in future releases. It is strongly advised to enable `require_certificate_validation` flag or explicitly set `cert` configuration to `True` for security reasons. You may receive an error after that if your SSL setup is incorrect.
[2025-07-07T06:47:01.738+0000] {subprocess.py:93} INFO - You may opt into the new behavior sooner by setting `flags.require_certificate_validation` to `True` in `dbt_project.yml`.
[2025-07-07T06:47:01.738+0000] {subprocess.py:93} INFO - Visit https://docs.getdbt.com/reference/global-configs/behavior-changes for more information.
[2025-07-07T06:47:03.127+0000] {subprocess.py:93} INFO - [0m06:47:03  1 of 3 START sql table model default_marts.fct_summary ......................... [RUN]
[2025-07-07T06:47:03.960+0000] {subprocess.py:93} INFO - [0m06:47:03  1 of 3 ERROR creating sql table model default_marts.fct_summary ................ [[31mERROR[0m in 0.83s]
[2025-07-07T06:47:03.963+0000] {subprocess.py:93} INFO - [0m06:47:03  2 of 3 START sql table model default_staging.my_first_dbt_model ................ [RUN]
[2025-07-07T06:47:04.330+0000] {subprocess.py:93} INFO - [0m06:47:04  2 of 3 OK created sql table model default_staging.my_first_dbt_model ........... [[32mCREATE TABLE (2 rows)[0m in 0.37s]
[2025-07-07T06:47:04.335+0000] {subprocess.py:93} INFO - [0m06:47:04  3 of 3 START sql view model default_staging.my_second_dbt_model ................ [RUN]
[2025-07-07T06:47:04.452+0000] {subprocess.py:93} INFO - [0m06:47:04  3 of 3 OK created sql view model default_staging.my_second_dbt_model ........... [[32mCREATE VIEW[0m in 0.11s]
[2025-07-07T06:47:04.455+0000] {subprocess.py:93} INFO - [0m06:47:04
[2025-07-07T06:47:04.455+0000] {subprocess.py:93} INFO - [0m06:47:04  Finished running 2 table models, 1 view model in 0 hours 0 minutes and 2.76 seconds (2.76s).
[2025-07-07T06:47:04.491+0000] {subprocess.py:93} INFO - [0m06:47:04
[2025-07-07T06:47:04.491+0000] {subprocess.py:93} INFO - [0m06:47:04  [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[2025-07-07T06:47:04.492+0000] {subprocess.py:93} INFO - [0m06:47:04
[2025-07-07T06:47:04.492+0000] {subprocess.py:93} INFO - [0m06:47:04  [31mFailure in model fct_summary (models/marts/fct_summary.sql)[0m
[2025-07-07T06:47:04.492+0000] {subprocess.py:93} INFO - [0m06:47:04    Database Error in model fct_summary (models/marts/fct_summary.sql)
[2025-07-07T06:47:04.493+0000] {subprocess.py:93} INFO -   TrinoExternalError(type=EXTERNAL, name=DELTA_LAKE_BAD_WRITE, message="Failed to write Delta Lake transaction log entry", query_id=20250707_064703_00019_884xn)
[2025-07-07T06:47:04.493+0000] {subprocess.py:93} INFO -   compiled code at target/run/dbt_lakehouse/models/marts/fct_summary.sql
[2025-07-07T06:47:04.493+0000] {subprocess.py:93} INFO - [0m06:47:04
[2025-07-07T06:47:04.493+0000] {subprocess.py:93} INFO - [0m06:47:04    compiled code at target/compiled/dbt_lakehouse/models/marts/fct_summary.sql
[2025-07-07T06:47:04.494+0000] {subprocess.py:93} INFO - [0m06:47:04
[2025-07-07T06:47:04.494+0000] {subprocess.py:93} INFO - [0m06:47:04  Done. PASS=2 WARN=0 ERROR=1 SKIP=0 NO-OP=0 TOTAL=3
[2025-07-07T06:47:04.892+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-07T06:47:04.893+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-07T06:47:04.900+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-07T06:47:04.904+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_run_lakehouse_project, task_id=dbt_run_all, run_id=scheduled__2025-07-05T10:00:00+00:00, execution_date=20250705T100000, start_date=20250707T064657, end_date=20250707T064704
[2025-07-07T06:47:04.911+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task dbt_run_all (Bash command failed. The command returned a non-zero exit code 1.; 1184)
[2025-07-07T06:47:04.940+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-07T06:47:04.970+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-07T06:47:04.973+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-07-07T07:27:02.063+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-07T07:27:02.091+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_lakehouse_project.dbt_run_all scheduled__2025-07-05T10:00:00+00:00 [queued]>
[2025-07-07T07:27:02.097+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_lakehouse_project.dbt_run_all scheduled__2025-07-05T10:00:00+00:00 [queued]>
[2025-07-07T07:27:02.097+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-07T07:27:02.111+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run_all> on 2025-07-05 10:00:00+00:00
[2025-07-07T07:27:02.120+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_lakehouse_project', 'dbt_run_all', 'scheduled__2025-07-05T10:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpe82e61tj']
[2025-07-07T07:27:02.122+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask dbt_run_all
[2025-07-07T07:27:02.123+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1213) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-07T07:27:02.124+0000] {standard_task_runner.py:63} INFO - Started process 1215 to run task
[2025-07-07T07:27:02.155+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_lakehouse_project.dbt_run_all scheduled__2025-07-05T10:00:00+00:00 [running]> on host fb8ac4917e48
[2025-07-07T07:27:02.213+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_lakehouse_project' AIRFLOW_CTX_TASK_ID='dbt_run_all' AIRFLOW_CTX_EXECUTION_DATE='2025-07-05T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-05T10:00:00+00:00'
[2025-07-07T07:27:02.214+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-07T07:27:02.226+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-07T07:27:02.227+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt_lakehouse && dbt run']
[2025-07-07T07:27:02.239+0000] {subprocess.py:86} INFO - Output:
[2025-07-07T07:27:04.118+0000] {subprocess.py:93} INFO - [0m07:27:04  Running with dbt=1.10.3
[2025-07-07T07:27:04.150+0000] {subprocess.py:93} INFO - INFO:trino.auth:keyring module not found. OAuth2 token will not be stored in keyring.
[2025-07-07T07:27:04.152+0000] {subprocess.py:93} INFO - INFO:trino.auth:keyring module not found. OAuth2 token will not be stored in keyring.
[2025-07-07T07:27:04.342+0000] {subprocess.py:93} INFO - [0m07:27:04  Registered adapter: trino=1.9.2
[2025-07-07T07:27:04.528+0000] {subprocess.py:93} INFO - [0m07:27:04  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-07-07T07:27:04.529+0000] {subprocess.py:93} INFO - There are 2 unused configuration paths:
[2025-07-07T07:27:04.529+0000] {subprocess.py:93} INFO - - models.dbt_lakehouse.staging
[2025-07-07T07:27:04.529+0000] {subprocess.py:93} INFO - - models.dbt_lakehouse.intermediate
[2025-07-07T07:27:04.667+0000] {subprocess.py:93} INFO - [0m07:27:04  Found 3 models, 6 data tests, 1 source, 454 macros
[2025-07-07T07:27:04.669+0000] {subprocess.py:93} INFO - [0m07:27:04
[2025-07-07T07:27:04.669+0000] {subprocess.py:93} INFO - [0m07:27:04  Concurrency: 1 threads (target='dev')
[2025-07-07T07:27:04.669+0000] {subprocess.py:93} INFO - [0m07:27:04
[2025-07-07T07:27:04.718+0000] {subprocess.py:93} INFO - [0m07:27:04  [[33mWARNING[0m]: SSL certificate validation is disabled by default. It is legacy behavior which will be changed in future releases. It is strongly advised to enable `require_certificate_validation` flag or explicitly set `cert` configuration to `True` for security reasons. You may receive an error after that if your SSL setup is incorrect.
[2025-07-07T07:27:04.719+0000] {subprocess.py:93} INFO - You may opt into the new behavior sooner by setting `flags.require_certificate_validation` to `True` in `dbt_project.yml`.
[2025-07-07T07:27:04.719+0000] {subprocess.py:93} INFO - Visit https://docs.getdbt.com/reference/global-configs/behavior-changes for more information.
[2025-07-07T07:27:06.367+0000] {subprocess.py:93} INFO - [0m07:27:06  1 of 3 START sql table model default_marts.fct_summary ......................... [RUN]
[2025-07-07T07:27:07.184+0000] {subprocess.py:93} INFO - [0m07:27:07  1 of 3 OK created sql table model default_marts.fct_summary .................... [[32mCREATE TABLE (3 rows)[0m in 0.81s]
[2025-07-07T07:27:07.187+0000] {subprocess.py:93} INFO - [0m07:27:07  2 of 3 START sql table model default_staging.my_first_dbt_model ................ [RUN]
[2025-07-07T07:27:07.472+0000] {subprocess.py:93} INFO - [0m07:27:07  2 of 3 ERROR creating sql table model default_staging.my_first_dbt_model ....... [[31mERROR[0m in 0.28s]
[2025-07-07T07:27:07.477+0000] {subprocess.py:93} INFO - [0m07:27:07  3 of 3 SKIP relation default_staging.my_second_dbt_model ....................... [[33mSKIP[0m]
[2025-07-07T07:27:07.482+0000] {subprocess.py:93} INFO - [0m07:27:07
[2025-07-07T07:27:07.482+0000] {subprocess.py:93} INFO - [0m07:27:07  Finished running 3 table models in 0 hours 0 minutes and 2.81 seconds (2.81s).
[2025-07-07T07:27:07.529+0000] {subprocess.py:93} INFO - [0m07:27:07
[2025-07-07T07:27:07.529+0000] {subprocess.py:93} INFO - [0m07:27:07  [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[2025-07-07T07:27:07.530+0000] {subprocess.py:93} INFO - [0m07:27:07
[2025-07-07T07:27:07.530+0000] {subprocess.py:93} INFO - [0m07:27:07  [31mFailure in model my_first_dbt_model (models/example/my_first_dbt_model.sql)[0m
[2025-07-07T07:27:07.531+0000] {subprocess.py:93} INFO - [0m07:27:07    Database Error in model my_first_dbt_model (models/example/my_first_dbt_model.sql)
[2025-07-07T07:27:07.531+0000] {subprocess.py:93} INFO -   TrinoExternalError(type=EXTERNAL, name=DELTA_LAKE_BAD_WRITE, message="Failed to write Delta Lake transaction log entry", query_id=20250707_072707_00020_kn9qh)
[2025-07-07T07:27:07.532+0000] {subprocess.py:93} INFO -   compiled code at target/run/dbt_lakehouse/models/example/my_first_dbt_model.sql
[2025-07-07T07:27:07.532+0000] {subprocess.py:93} INFO - [0m07:27:07
[2025-07-07T07:27:07.532+0000] {subprocess.py:93} INFO - [0m07:27:07    compiled code at target/compiled/dbt_lakehouse/models/example/my_first_dbt_model.sql
[2025-07-07T07:27:07.533+0000] {subprocess.py:93} INFO - [0m07:27:07
[2025-07-07T07:27:07.533+0000] {subprocess.py:93} INFO - [0m07:27:07  Done. PASS=1 WARN=0 ERROR=1 SKIP=1 NO-OP=0 TOTAL=3
[2025-07-07T07:27:07.858+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-07T07:27:07.859+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-07T07:27:07.868+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-07T07:27:07.873+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_run_lakehouse_project, task_id=dbt_run_all, run_id=scheduled__2025-07-05T10:00:00+00:00, execution_date=20250705T100000, start_date=20250707T072702, end_date=20250707T072707
[2025-07-07T07:27:07.904+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task dbt_run_all (Bash command failed. The command returned a non-zero exit code 1.; 1215)
[2025-07-07T07:27:07.922+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-07T07:27:07.937+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-07T07:27:07.987+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
