[2025-07-05T17:13:27.379+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-05T17:13:27.400+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lakehouse_pipeline.silver_to_gold manual__2025-07-05T17:12:56.382227+00:00 [queued]>
[2025-07-05T17:13:27.406+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lakehouse_pipeline.silver_to_gold manual__2025-07-05T17:12:56.382227+00:00 [queued]>
[2025-07-05T17:13:27.406+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-05T17:13:27.415+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): silver_to_gold> on 2025-07-05 17:12:56.382227+00:00
[2025-07-05T17:13:27.422+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'lakehouse_pipeline', 'silver_to_gold', 'manual__2025-07-05T17:12:56.382227+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmppkprmnlj']
[2025-07-05T17:13:27.424+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask silver_to_gold
[2025-07-05T17:13:27.425+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=477) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-05T17:13:27.425+0000] {standard_task_runner.py:63} INFO - Started process 478 to run task
[2025-07-05T17:13:27.452+0000] {task_command.py:426} INFO - Running <TaskInstance: lakehouse_pipeline.silver_to_gold manual__2025-07-05T17:12:56.382227+00:00 [running]> on host feee970e76b0
[2025-07-05T17:13:27.505+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lakehouse_pipeline' AIRFLOW_CTX_TASK_ID='silver_to_gold' AIRFLOW_CTX_EXECUTION_DATE='2025-07-05T17:12:56.382227+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-05T17:12:56.382227+00:00'
[2025-07-05T17:13:27.505+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-05T17:13:36.371+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-05T17:13:36.372+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/silver_to_gold.py", line 24, in run
    summary = df.groupBy("customer_id").sum("amount").withColumnRenamed("sum(amount)", "total_amount")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/group.py", line 49, in _api
    jdf = getattr(self._jgd, name)(_to_seq(self.session._sc, cols))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/errors/exceptions/captured.py", line 175, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: "amount" is not a numeric column. Aggregation function can only be applied on a numeric column.
[2025-07-05T17:13:36.386+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=lakehouse_pipeline, task_id=silver_to_gold, run_id=manual__2025-07-05T17:12:56.382227+00:00, execution_date=20250705T171256, start_date=20250705T171327, end_date=20250705T171336
[2025-07-05T17:13:36.399+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task silver_to_gold ("amount" is not a numeric column. Aggregation function can only be applied on a numeric column.; 478)
[2025-07-05T17:13:36.445+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-05T17:13:36.466+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-05T17:13:36.470+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
